#!/bin/bash

if [ "$(id -u)" != "0" ]; then
	echo "This script must be run as root!"
	exit 1
else
	cd src
	mkdir -p /usr/{bin,share/cdmf}
	install -m755 /cdm /usr/bin/
	cp -Rf cdmrc skel themes /usr/share/cdm/
	echo "CDM configuration is done through /usr/share/cdm/cdmrc"
	echo "Replace ~/.xinitrc and ~/.bash_profile with the skel files in /usr/share/cdm/skel for each user."
fi
