#!/bin/bash

if [ "$(id -u)" != "0" ]; then
	echo "This script must be run as root!"
	exit 1
else
	cd src
	mkdir -p /usr/{bin,share/cdm}
	install -m755 cdm /usr/bin/
	install -Dm644 cdmrc /etc/cdmrc
	install -Dm755 zzz-cdm-profile.sh /etc/profile.d/zzz-cdm-profile.sh
	cp -Rf themes /usr/share/cdm/
fi
