#!/bin/sh
#
# If option usexinit is set then this file is not used.  Instead ~/.xinitrc
# if it exists or else /etc/X11/xinit/xinitrc is used in it's place.


# Put your configuration above this line.

wm_bin="$1"
exec ${wm_bin}
